### ISSUE TITLE
unable to add a survey to the client

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1324]
## Description
unable to add a survey to the client

## Steps to Reproduce
1. first create a basic survey at admin->system->manage surveys
2. go to institution->client and select any client
3. in client screen go to more and click on survey
4. click on take survey and select a survey
5. now submit the survey

## Expected Behaviour
user should be able to submit the survey successfully

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/113413599-a7101480-93d8-11eb-958d-ec72688d01b9.png)

**Comment by elizamota** [comment]
After inspecting the errors produced by the submit button I found that the first error produced would be solved by an Access-Control-Allow-Origin header. This error is produced when the browser refuses access to a remote resource which usually happens when trying to execute a cross domain request. There is also a chrome extension that can be used to fix this error temporarily which is what I used. The second error was a POST 500 error which is caused by the api and cannot be fixed from the client end. I would suggest revising the api or using an api with different information to see if you receive a different outcome.

<img width="1437" alt="Screen Shot 2021-04-13 at 9 13 20 PM" src="https://user-images.githubusercontent.com/61021048/115124163-d6a14e00-9f8e-11eb-820e-ed89a594b1ac.png">
<img width="1437" alt="Screen Shot 2021-04-13 at 8 40 27 PM" src="https://user-images.githubusercontent.com/61021048/115124167-def98900-9f8e-11eb-80a3-4d8307564c72.png">
<img width="1360" alt="Screen Shot 2021-04-15 at 8 06 37 PM" src="https://user-images.githubusercontent.com/61021048/115124170-e3be3d00-9f8e-11eb-90db-d83de68ad708.png">

**Comment by bharathcgowda** [comment]
thank you for the analysis and detailed explanation @elizamota, @BLasan  will you be able to look into this issue once?

**Comment by BLasan** [comment]
@bharathcgowda I think this is not an issue with the server. I tried the same surveys as in @elizamota 's Screenshots. But I'm not getting any issues. I think this needs to be fixed in the front-end. No issues with the released version of Mifos (Community-App).
Try the same scenarion using the host `https://dev.mifos.io`

**Comment by elizamota** [comment]
Both @bharathcgowda and I were on the local host when the error appeared so it could just be the Access-Control-Allow-Origin header. If you tried the same scenario on the local host it would produce the error from the original issue.

**Comment by BLasan** [comment]
@bharathcgowda  @elizamota 
![Screenshot from 2021-04-19 18-14-44](https://user-images.githubusercontent.com/43112139/115238318-2e7cb800-a13b-11eb-84f6-aa9115d35153.png)

**Comment by JemCdo** [comment]
@BLasan @elizamota @bharathcgowda I had a same issue today on https://github.com/openMF/web-app but then I switched to https://github.com/openMF/community-app/ and everything is working fine on same same server as tested by @BLasan

**Comment by bharathcgowda** [comment]
Right,thank you for testing this @JemCdo.
 
We have to fix the issue on the web-app project as well.

**Comment by CesarCrZy** [comment]
I´ve found the issue under src/app/clients/clients-view/clients-actions/take-survey/take-survey.component.ts 

The way to get **clientId** is wrong, so when the request send, **clientId** is undefined, the parameter for get that id should be **this.route.parent.snapshot.paramMap.get("clientId");** but its written **this.route.parent.parent.snapshot.paramMap.get("clientId");**

**Comment by bharathcgowda** [comment]
Hi @CesarCrZy  thank you for finding the root cause, will you be able send a PR for the same?

**Comment by CesarCrZy** [comment]
Sure!

**Comment by ramvr1256** [comment]
The issue is blocked due to API failure. Fineract ticket is raised `https://issues.apache.org/jira/browse/FINERACT-1636`
