### ISSUE TITLE
Docker Build fails from Docker file

### ISSUE THREAD

**Issue by T-lang** [openMF/web-app#1340]
## Description
Setting up the application with Docker fails in step 9/11

## Steps to Reproduce
1. Install Docker
2. git clone https://github.com/openMF/web-app.git
3. docker build -t openmf/web-app:latest .

## Expected Behaviour
Build Application

## Actual Behaviour
Fail in build from line 
COPY --from=builder /usr/src/app/dist/web-app /usr/share/nginx/html
Output: COPY failed: stat usr/src/app/dist/web-app: file does not exist

**Comment by Chathu94** [comment]
+1

**Comment by tk512** [comment]
/app/dist/web-app /usr/share/nginx/html
> Output: COPY failed: stat usr/src/app/dist/web-app: file does not exist

The docker build fails here because the environment.ts or environment.prod.ts files in your src/environment folder is lacking variables.  These are normally found in .env, but if you do not have that, it won't build.

You will need to create an .env file like the following before running the docker build:

```
allow_switching_backend_instance=true
mifos_x_version=
```

**Comment by Noe-Garcia** [comment]
Hi, check this PR to solve this problem https://github.com/openMF/web-app/pull/1344
