### ISSUE TITLE
Unable to create any product account(loans/FD and RD accounts)

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1400]
## Description
unable to create any account (loans/FD and RD accounts)

## Steps to Reproduce
1. go to any client
2. go to applications-> create new loan account
3. there is no submit button for loan account
4. only next (disabled) button

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/169596783-4e21cc5e-55a0-4fc6-bc12-fae1ead92730.png)
![image](https://user-images.githubusercontent.com/65952533/169597192-aec1f601-bb8a-4692-a075-25f30ccc03c7.png)

**Comment by adamsaghy** [comment]
**Observation**
Cannot complete the loan creation as it shows validation error for the "Terms".
The network tab (request-responses) are clear
The Console log is clear.
There is not much information what goes wrong...


**Use cases**
1. When "Digital Loan" is selected as Product, on the Terms page there is validation error, but the UI shows nothing and the console log is not helping either.
2. When "Digital Term Loan" is selected, during the submit there is an error:
{"developerMessage":"The request was invalid. This typically will happen due to validation errors which are provided.","httpStatusCode":"400","defaultUserMessage":"Validation errors exist.","userMessageGlobalisationCode":"validation.msg.validation.errors.exist","errors":[{"developerMessage":"The parameter recalculationCompoundingFrequencyDate is not supported.","defaultUserMessage":"The parameter recalculationCompoundingFrequencyDate is not supported.","userMessageGlobalisationCode":"error.msg.parameter.unsupported","parameterName":"recalculationCompoundingFrequencyDate","value":null,"args":[{"value":"recalculationCompoundingFrequencyDate"}]}]}

**Description**: Specifies compounding frequency start date for interest recalculation. This date must be equal to disbursement date, 
However there is no such field in Fineract... :/
https://issues.apache.org/jira/browse/FINERACT-60 -> Open issue

3. Create recurring deposit account
First you need to create a Recurring Deposit Product, but it is not working as of now:
{"timestamp":"2022-05-24T23:36:58.887+00:00","status":500,"error":"Internal Server Error","path":"/fineract-provider/api/v1/recurringdepositproducts/5"}

It requires further investigation...

4. I was able to create Savings account... Client id: 1, Savings id: 15

5. To apply for share account, first we need to setup Share product

**Comment by bharathcgowda** [comment]
currently being worked by Ramveer
https://github.com/ramvr1256

**Comment by adamsaghy** [comment]
FD account creation is fixed

**Comment by adamsaghy** [comment]
RD account creation is working

**Comment by adamsaghy** [comment]
Share account creation is working

**Comment by adamsaghy** [comment]
Loan account creation is working

**Comment by bharathcgowda** [comment]
@adamsaghy  awesome :)
