### ISSUE TITLE
make repayment not working

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1401]
## Description
make repayment not working

## Steps to Reproduce
1. go to any active loan accounts
2. click submit button

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/169597894-a1631f96-0d4a-4021-802f-c370339304fd.png)

**Comment by adamsaghy** [comment]
**Observation**
The repayment happens but the afterward page redirect is not. For unknown reasons the webapp is trying to fetch data from "/loans/general?associations=all&exclude=guarantors,futureSchedule" which is a not existing endpoint.

**Proposed solution**
Must debug the WebApp scripts and find the spot where instead of the loan id it inject the "general" word into the API endpoint.

**Comment by adamsaghy** [comment]
Works again, however some of the already existing accounts are in invalid state.
