### ISSUE TITLE
New Data Tables Creation not working

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1402]
## Description
New Data Tables Creation not working

## Steps to Reproduce
1. go to admin->systems->manage data tables
2. click 'create data table, add all the fields and click on submit
3.

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/170038434-6a5edd2f-6103-455b-b2e0-da5ca279cb54.png)

**Comment by adamsaghy** [comment]
**Observation**
Seems Fineract would like to get one more parameter: "entitySubType"

**Here is the error message:**
defaultUserMessage: "Validation errors exist."
developerMessage: "The request was invalid. This typically will happen due to validation errors which are provided."
errors: [{developerMessage: "The parameter entitySubType is mandatory.",…}]
0: {developerMessage: "The parameter entitySubType is mandatory.",…}
httpStatusCode: "400"
userMessageGlobalisationCode: "validation.msg.validation.errors.exist"

**Reason**
If the "Application Table Name" is Client, there must be providing an another entry (entitySubType) which shall decide the client is a Person or a Non-Person (Entity).
https://issues.apache.org/jira/browse/FINERACT-1375 

**Proposed solution**
If "CLIENT" is the selected application table, on the UI an extra field should to be added where it can be selected whether the client is a PERSON or an ENTITY.

**Comment by adamsaghy** [comment]
Fixed
