### ISSUE TITLE
Trache Addition screen for Loan account issue

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1442]
## Description
for a loan account with tranche enabled, the "loan tranche details tab" should just have a + sign to add the tranche and not the tranche addition row by default.

Now 
![image](https://user-images.githubusercontent.com/65952533/174538650-2fbe52f5-8a01-4862-a6e8-052623d5d762.png)

Example screen from community-app
![image](https://user-images.githubusercontent.com/65952533/174538716-29fb6a18-55a6-45e4-9d15-dda24a37a1c7.png)

**Comment by ramvr1256** [comment]
I added this row because a tranche-enabled loan account can not be submitted without any entry as you can try this on default.ps.mifos.io. At least one entry is needed to submit a loan application. Do you still want to remove this row? This may lead users not identify the cause of not submitting. Currently, they can at least they will be prompted to fill this required field.

**Comment by bharathcgowda** [comment]
@ramvr1256  There is a configuration that enables users to do multi-disbursements without adding a tranche, there is no UI yet for this configuration but is being used by some of the organizations. this change is affecting the loan creations for such products, let's revert as discussed in this ticket. 

You can refer to this PR for more details as well
https://github.com/apache/fineract/commit/bd8dab19467841e4a26cdf0f47b31085702cd980

**Comment by bharathcgowda** [comment]
fixed
