### ISSUE TITLE
Add group button doesn't work

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1560]
## Description

Add group button does nothing:
- doesn't send a network call

## Steps to Reproduce

1. Create Center.
2. Create Group.
3. Assign Group to Center using Add Group button.

## Expected Behaviour

Opens the list of group? or something else?

## Actual Behaviour

Does nothing.

## Settings
- Mifos X version: https://sandbox.mifos.community/
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

Assign Group: 
<img width="1440" alt="Screenshot 2022-11-13 at 4 19 58 PM" src="https://user-images.githubusercontent.com/4143778/201518007-383cf5d0-fb57-455b-ac4d-421517d8ebd5.png">

Groups:
<img width="1440" alt="Screenshot 2022-11-13 at 4 23 29 PM" src="https://user-images.githubusercontent.com/4143778/201518022-ff015bb7-11ec-49e5-9452-04dc17221343.png">

GIF:

https://user-images.githubusercontent.com/4143778/201518029-a6d37195-f821-4322-8020-b025aafda0ea.mov

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@anika-001  could you please review this issue?

**Comment by anika-001** [comment]
Hi, we don't have any action/event assigned on click to the button at the moment, hence, when clicking on the button, nothing happens. (added code image)
![image](https://user-images.githubusercontent.com/62497183/202929503-6cc13578-04c0-4640-9159-2aa57d86ffbb.png)

Is there a specific activity/event we've to direct the click to, I can work on it if you could share more about the expected behavior of the button after click.

**Comment by bharathcgowda** [comment]
@anika-001 could you see here https://default.ps.mifos.io/ (mifos/password)
This is first UI, analysing here will help you in understanding the Pointing APIs

**Comment by tapaswenipathak** [comment]
Doesn't work.


https://user-images.githubusercontent.com/4143778/215327384-8e5ad272-6717-4854-96d7-aa445cc7252c.mov
