### ISSUE TITLE
Add Clients button doesn't work

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1564]
## Description

Add Client button does nothing.

## Steps to Reproduce
1. Go to Groups.
2. Click on Group Head Office (any)
3. On https://sandbox.mifos.community/#/groups/6/general, click on Add Clients button.

## Expected Behaviour

Something?

## Actual Behaviour

Nothing happens.

## Settings
- Mifos X version: https://sandbox.mifos.community/#/groups/6/general
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

Add Clients:

<img width="1422" alt="Screenshot 2022-11-13 at 5 45 16 PM" src="https://user-images.githubusercontent.com/4143778/201521180-8dd85e0e-2e5f-40af-9b58-26b426c23372.png">

Screen Recording:

https://user-images.githubusercontent.com/4143778/201521194-a85c1dd3-cc2e-4038-bf17-d366b8fdadfd.mov

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by anika-001** [comment]
Hi, we don't have any event assigned on click to the button at the moment, hence, when clicking on the button, nothing happens. (added code image)
![image](https://user-images.githubusercontent.com/62497183/202929141-cd3889ea-d562-4307-b8a2-2395d3fdc5fb.png)

Is there a specific activity/event we've to direct the click to, I can work on it if you could share more about the expected behavior of the button after click.

**Comment by bharathcgowda** [comment]
@anika-001  could you see here https://default.ps.mifos.io/ (mifos/password)
This is first UI, analysing here will help you in understanding the Pointing APIs

**Comment by tapaswenipathak** [comment]
Seems like UI is changed. There are no buttons for the features now. Back button doesn't work.


https://user-images.githubusercontent.com/4143778/215326947-37f2a51c-70a3-4203-a005-40b193861234.mov

<img width="1437" alt="Screenshot 2023-01-29 at 6 14 21 PM" src="https://user-images.githubusercontent.com/4143778/215326980-00d5b639-af54-4120-8ba9-0ed076637cfe.png">
