### ISSUE TITLE
Gender not getting updated while creating client: No dropdown or text writing enabled

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1663]
Ref https://github.com/openMF/web-app/issues/1566#issuecomment-1407632836.

Not able to reopen issue.

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

**Comment by Subzer0570** [comment]
hello @tapaswenipathak 
Can I work on this issue?
(If possible can I provide some context where to check for the bug @edcable)

**Comment by PC-11-00** [comment]
@tapaswenipathak You added codes in a different website(https://demo.mifos.community/#/system) and tried to access it on another website(https://sandbox.mifos.community/#/clients/create), that's why it was not showing options.

https://user-images.githubusercontent.com/76156941/220026882-d57d462d-ba7e-446c-bff8-881c0edb0fc6.mov
