### ISSUE TITLE
Manage Reports: Report  list

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#173]
Goal:
As a system admin, I must  be  able to view all existing report templates:

https://demo.openmf.org/#/reports
![managereports](https://user-images.githubusercontent.com/23022667/43184511-7626a3ee-9006-11e8-8793-6d4912619c07.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895354/Manage+Reports

**Comment by Verdiane** [comment]
Hi abhaychawla, I will like to work on this issue

**Comment by abhaychawla** [comment]
You can only work on a single issue at a time. Please do not claim multiple issues at once.

**Comment by kerlynNkep** [comment]
Hello @abhaychawla please can i work on this Issue

**Comment by abhaychawla** [comment]
@kerlynNkep let me review your PRs and get back to you in a day.

**Comment by kerlynNkep** [comment]
Okay i'll be waiting

**Comment by Verdiane** [comment]
Hello @abhaychawla , I have already seen a PRs for the other one. Please can you also review it

**Comment by Verdiane** [comment]
Hey @abhaychawla , I am just from sending a PR for this issue. Please can I start working on a new issue while you review these ones. Thanks

**Comment by abhaychawla** [comment]
You can work on another issue but you should ask first. If you do it in this manner it will be at your own risk. This is not a competition. I already told you not to claim two issues simultaneously. You didn't ask to work on this issue once you sent the earlier PR. There was already a contributor who had asked and I asked them to wait because I had to ensure something before I could ask her to work on it. Due to this, I will be closing the PR you have sent for this issue.

**Comment by karantakalkar** [comment]
@abhaychawla 
i have completed my PR for issue #210 , can i work on this please?

**Comment by abhaychawla** [comment]
Fixed by: https://github.com/openMF/web-app/pull/405
