### ISSUE TITLE
Loading bar does not stop loading on login

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1793]
## Description
The loading bar our Mifos X tenant loads persistently without stopping

## Steps to Reproduce

1. Visit the site: https://corebanking2.test.vggdev.com
3. Login successfully into the application, on the dashboard, and any other page visited, it was observed, the top loading bar below the menu does not stop loading

## Expected Behaviour
Upon loading of item, loading progress bar should stop

## Actual Behaviour
loading progress bar loads persistently

## Settings
- Mifos X version: 1.8.4
- Browser used: Edge, Chrome

## Screenshots, if any
<img width="1397" alt="ProgressBarPersistentLoading" src="https://github.com/openMF/web-app/assets/11774340/0bf27103-902f-4cdc-856d-2793546d11da">

**Comment by Thanush66** [comment]
is this issue solved?? i think i can fix it

**Comment by PC-11-00** [comment]
It totally depends on your internet connection, if you lose it, the webpage will try to make a request to the backend, but will not receive any response, that's why it doesn't stop. It's working fine for me.
https://github.com/openMF/web-app/assets/76156941/574adc43-cf3f-4f54-aa6d-26283be27433

**Comment by bharathcgowda** [comment]
@Thanush66  can you take a look into this? ..it is still not fixed.

**Comment by bharathcgowda** [comment]
as per analysis from @PC-11-00  this is not a front end issue
It doesn’t stop remotely,  there can be few reasons:
The websites which are hosted on some platform can be slow ,to receive any response
Same for the backend as above where it is hosted
In this issue, progress bar didn’t stop after loading even the page, the reason behind this is Angular is a single page application, and when he clicks on anything ,it might appear something because it is a single page, but some request may be sent to the backend and progress starts and it will stop only when it will receive any response.
