### ISSUE TITLE
View user details shows a different user

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1794]
## Description
Trying to View user details of a particular mifos user, the details displayed are that of another user

## Steps to Reproduce
Visit site

1. Login with credentials
2. Click on the Self Service Option on the Menu bar -> Click the User Management menu from the drop-down link. List of users is displayed
3. Clicking on any user displays the same user details, please see the screenshots below

## Expected Behaviour
Should be able to see the details of the user selected

## Actual Behaviour
On select a user to view its details, I am unable to see the details of the selected user but of another

## Settings
- Mifos X version: 1.8.4
- Browser used: Chrome, Edge

## Screenshots, if any
<img width="1397" alt="userdetails1" src="https://github.com/openMF/web-app/assets/11774340/65cb067d-faf2-4d88-bd53-b9545ad01005">
<img width="1397" alt="userdetails2" src="https://github.com/openMF/web-app/assets/11774340/b103e31f-ac3f-47c5-a4e5-0ce9f398f9f5">

**Comment by nikhil-sh-93** [comment]
Hello skemuel007, the reason why this fails because in the user service where you invoke the getUser method its returning a .json file pointing at the asset folder which contains only one object
<img width="372" alt="Screenshot 2023-07-19 135614" src="https://github.com/openMF/web-app/assets/100997822/b9e19d83-0501-40ff-afc3-be1df807016e">

**Comment by skemuel007** [comment]
Hello @bharathcgowda please can you provide the needed API endpoint so @nikhil-sh-93 can fix this

**Comment by bharathcgowda** [comment]
@skemuel007  as I verified this is related to the self service module that is depending on the sepf service APIs https://demo.mifos.io/api-docs/apiLive.htm#selfoauth

There is no API built for list of User details from the User module. also self service APIs are not being worked on currently due to security reasons this development could not be happening anytime soon.

Also, I do not see any use case of the Advancly where they use self service module.
Hence closing this as not planned
