### ISSUE TITLE
Issues building PR 2059 with Docker

### ISSUE THREAD

**Issue by ichux** [openMF/web-app#2060]
## Description
I tried to build https://github.com/openMF/web-app/pull/2059 but I get **Inlining of fonts failed. An error has occurred while retrieving https://fonts.googleapis.com/icon?family=Material+Icons over the internet.**

@alberto-art3ch FYI

Does [this](https://stackoverflow.com/a/73617389) help?

## Steps to Reproduce
`BUILDKIT_PROGRESS=plain docker build -t mifos-community-app .`

## Screenshots, if any
![bugs](https://github.com/openMF/web-app/assets/30695966/87a5128d-a01a-455c-8761-186eb35ce320)

**Comment by ichux** [comment]
When I commented both lines that had fonts.googleapis.com in it, the compilation worked!

FYI: I don't use any VPN

**Comment by alberto-art3ch** [comment]
Hello!Do you want or not to use those fonts?Because is the answer is yes, we can include those files as part of the projectThanks and best regardsAlbertoOn 31 Mar 2024, at 5:51 a.m., Chukwudi Nwachukwu ***@***.***> wrote:﻿
Description
I tried to build #2059 but I get Inlining of fonts failed. An error has occurred while retrieving https://fonts.googleapis.com/icon?family=Material+Icons over the internet.
@alberto-art3ch FYI
Steps to Reproduce
BUILDKIT_PROGRESS=plain docker build -t mifos-community-app .
Screenshots, if any
bugs.png (view on web)

**Comment by ichux** [comment]
> Hello! Do you want or not to use those fonts? Because is the answer is yes, we can include those files as part of the project Thanks and best regards>

@alberto-art3ch it will suggest we go the route of including the files as part of the project. I was able to get it to work when I commented them out but after that, I uncommented them back in the deployed index.html file.

Thanks
