### ISSUE TITLE
Groups: Create Group page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#212]
Goal: 
As a loan officer, I want to create a group under center which is assigned to me as shown here:
https://demo.openmf.org/#/creategroup
![create group](https://user-images.githubusercontent.com/23022667/43200648-cefb7cc4-9033-11e8-8e98-deb552a51561.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895334/Manage+Groups
https://demo.openmf.org/api-docs/apiLive.htm#groups_create

**Comment by meetcric** [comment]
should i take working on this? @abhaychawla

**Comment by meetcric** [comment]
can I start working on this? @abhaychawla

**Comment by meetcric** [comment]
should i take this? @abhaychawla @santoshconflux

**Comment by meetcric** [comment]
Hi @abhaychawla 
Actually, I am unable to find the API of "selecting the available staff belonging to the particular office".
Can u help me figure out the required API.

**Comment by abhaychawla** [comment]
Please look at how it is being implemented in the community-app and replicate accordingly.

**Comment by meetcric** [comment]
Hello @abhaychawla,
Actually, I've been stuck on this issue from quite sometime now. I am confused about  field `datatables` given in the POST request .As their was no details in the wiki of create-group ,i am bit confuse now .
Please help me so that i can complete this issue.Thank you in advance.

![screenshot from 2019-01-11 01-12-43](https://user-images.githubusercontent.com/29123704/50993784-8120a000-1540-11e9-8ff4-54ffc23a4854.png)

![screenshot from 2019-01-11 01-12-37](https://user-images.githubusercontent.com/29123704/50993798-8251cd00-1540-11e9-86d4-95a2365daf2c.png)

**Comment by abhaychawla** [comment]
Did you explore the community-app?

**Comment by meetcric** [comment]
Hi @abhaychawla,
I'm trying to make a POST request for ''create group" but I'm facing this CORS error, Can you help me to resolve this error?
![screenshot from 2019-01-16 12-28-00](https://user-images.githubusercontent.com/29123704/51231929-31503780-198b-11e9-8b43-fc2204e8f340.png)

**Comment by abhaychawla** [comment]
The demo server is facing a few issues these days, please set up a local server or have a look at alternate ways to connect to the server on the mail I sent on the mailing list a few days ago to ensure smoother development.

**Comment by meetcric** [comment]
Thanks for the help @abhaychawla

**Comment by meetcric** [comment]
Thanks for the help @abhaychawla.
I have updated the API URL of the environment.ts file but still facing the same error and unable to figure out the reason.

**Comment by karantakalkar** [comment]
@abhaychawla 
Can i work here please?
