### ISSUE TITLE
Shares: Share Applications submitted/approved page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#231]
Goal:
Able to  view share application which is in submitted/approved state as shown here:
https://demo.openmf.org/#/viewshareaccount/134
![shares submitted-approval page](https://user-images.githubusercontent.com/23022667/43247051-304297cc-90d1-11e8-8fa5-a423207de6ec.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/4456584/Shares+Module
https://demo.openmf.org/api-docs/apiLive.htm#shareaccount_approve

**Comment by Mutahar-Majid** [comment]
Is this issue still open? I would like to work on this.

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by Mutahar-Majid** [comment]
@abhaychawla As I understood from the documentation and links provided, the share account table rows in the general client tab should redirect to share account page if there is a shared product under the client's name. 
![share-account-preview](https://user-images.githubusercontent.com/48222473/76161660-673a1780-615b-11ea-9aa1-0fc44cf56cb4.png)

So the view-share-account component should be created inside the client-view directory, right? Please correct me if I'm wrong anywhere.

**Comment by Mutahar-Majid** [comment]
@abhaychawla In view of the absence of transaction data overview API endpoint as mentioned in https://gitter.im/openMF/web-app, should I push the code with the transaction overview table code commented since we can later add it by just replacing the data source variable once it's available? Rest everything is coded as per requirements.
![Screen Shot 2020-03-30 at 5 40 42 PM](https://user-images.githubusercontent.com/48222473/77910997-b46a5e80-72ad-11ea-9068-86b995d1d705.png)
