### ISSUE TITLE
Default credentials  mifos/password not working

### ISSUE THREAD

**Issue by tkngambi** [openMF/web-app#374]
## Description
I followed instructions to install on a local Windows machine - I get the app running, but default MIfos X username and password (mifos/password) do not work.

## Steps to Reproduce
Please add as much detail as possible to reproduce the error/issue.
Don't assume the reader knows anything about the Mifos X Web App.

I followed the web app install instructions to a t.

## Expected Behaviour

Access to web app

## Actual Behaviour

username and password required

## Settings
- Mifos X version: Version 0.0.0-dev
- Browser used: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

## Screenshots, if any

![capture](https://user-images.githubusercontent.com/16385151/51967877-22807f00-2479-11e9-8dca-03747ce27904.JPG)
#help wanted

**Comment by abhaychawla** [comment]
@tkngambi The default credentials are valid, sometimes the demo server is unresponsive due to which you haven't been able to access the web-app. Alternately, you can access it by setting up a local server the instructions for which are present in README. Other methods include accessing it via the staging or mobile server for which please see my last post on the mailing list/take help from gitter. Kindly research properly before creating an issue from next time.
