### ISSUE TITLE
Error handling is not available for all the elements

### ISSUE THREAD

**Issue by tanujvyas10** [openMF/web-app#482]
**Is your feature request related to a problem? Please describe.**
Error handling is not available for all the inputs

**Describe the solution you'd like**
For each input element, error handling should be available

**Screen shot**

![mifos2](https://user-images.githubusercontent.com/48439116/69448653-01c64480-0d7f-11ea-9b79-f087719e5df1.jpeg)

**I would like to work on it**

**Comment by tanujvyas10** [comment]
@abhaychawla Sir,is this issue valid?

**Comment by beast-incarnate13** [comment]
@abhaychawla , would validation on certain fields such be useful? say, such as Routing Code, it is always going to be a number and likely to be restricted to 9 digits only. Such business related validation can be extended to other fields as well. Moreover, such fields can be rendered dynamically according to options selected by the user, for instance choosing Airtel Money as Payment Type should hide Options like Cheque Number, etc. 

If such enhancements seem relevant, can I contribute accordingly?

**Comment by abhaychawla** [comment]
@tanujvyas10 This specifically, is validation for mandatory fields that are supposed to be filled so it cannot be extended to all the fields as all are not mandatory. The one that you are referring to in the screenshot is not error handling which can be extended to every field, this issue is incorrect. All mandatory fields already have the required validation.

@beast-incarnate13 Such validations would depend upon the customizations being done by the community members who will be using this application. We cannot always be sure of what all options will be available or a field's length or whether it will accept a number only most things are customizable. You can send a mail to the mailing list to discuss about such business validations and get the thoughts of the community first. If there are some validations that will be helpful to all and are possible to implement can be implemented after discussion.
