### ISSUE TITLE
Language selector is not working.

### ISSUE THREAD

**Issue by tanujvyas10** [openMF/web-app#497]
**Is your feature request related to a problem? Please describe.**
Language selector is not working.

**Describe the solution you'd like**
Whenever the language is selected, the language of the whole domain of our web-app should be changed.

**Additional context**
![mifos_lang1](https://user-images.githubusercontent.com/48439116/70229461-4d63ef80-177c-11ea-8745-06965e04416c.jpeg)
![mifos_lang](https://user-images.githubusercontent.com/48439116/70229463-4dfc8600-177c-11ea-870e-0d6620f15cc0.jpeg)

**I would like to work on it.**

**Comment by abhaychawla** [comment]
@tanujvyas10 Adding translations to the web app is still being discussed within the community on the mailing list and with the other senior mentor. We want to use officially supported internationalization feature of Angular and not any 3rd party library, due to which we are still waiting for a official release from Angular for run-time translation support. As the web app is still in development and a decision hasn't been reached on translations, this is not a valid issue.

**Comment by BLasan** [comment]
@abhaychawla  Can I work on this?
