### ISSUE TITLE
The demo server is not responding with credentials {username: "mifos", password: "password"}

### ISSUE THREAD

**Issue by ashwaniYDV** [openMF/web-app#552]
## Description
The demo server is not responding with credentials {username: "mifos", password: "password"}

## Steps to Reproduce
1) Open the development server.
2) Login with credentials given in readme file.

## Expected Behaviour
User should be logged in.

## Actual Behaviour
The server is not responding.

## Settings
- Browser used: Chrome

**Comment by OussEmaDevCode** [comment]
@ashwaniYDV Hi, that's not really an issue related to this project, it's more of a server issue try going to `.\app\src\environments\environment.ts` and change the `baseApiUrl` to the new demo server "https://demo.mifos.io/" and everything should be fine !

**Comment by ashwaniYDV** [comment]
@OussEmaDevCode This time I'm getting "Cross-Origin Request Blocked". How to bypass cors issue. Please help.

**Comment by spider0061** [comment]
@ashwaniYDV are you working on web-app or are you using demo.openmf.org ?

**Comment by ashwaniYDV** [comment]
@spider0061 I am working on web-app.

**Comment by abhaychawla** [comment]
Hi @ashwaniYDV, this is not an issue. The credentials are working for https://demo.openmf.org. However, we are gradually shifting to the new demo server https://demo.mifos.io 
The credentials are valid for the same as well but the server for https://demo.mifos.io seems to be having some issues at this moment. I will get that checked. Once the issue is resolved, I will let everyone know at Gitter. Till then if all available servers are inaccessible, please try and set up a local server and use the same for development if required.
