### ISSUE TITLE
node-sass package required as a dependency

### ISSUE THREAD

**Issue by mdew192837** [openMF/web-app#72]
## Description
Running npm install does not install node-sass, which appears to be required to properly compile everything.

## Steps to Reproduce
1. Clone the repository
2. Run `npm install`
3. Run `npm start`
You will receive a compilation error similar to https://dpaste.de/zebp

## Expected Behaviour
The app compiles and the user can access the web-app on the localhost successfully.

## Actual Behaviour
The app does not compile and the web-app cannot be accessed.

## Settings
- Mifos X version: Latest
- Browser used: Chrome

**Comment by abhaychawla** [comment]
@mdew192837 Please try running `npm install` again. It should install all the required dependencies including node-sass. Some error might have occurred due to network issues on your side because of which it did not get installed earlier.

**Comment by mdew192837** [comment]
@abhaychawla 

The file https://github.com/openMF/web-app/blob/master/package.json does not have `node-sass` as a dependency, so thus running `npm-install` won't do anything.

**Comment by abhaychawla** [comment]
@mdew192837 The dev dependency mention in package.json `@angular-devkit/build-angular` requires `node-sass` to be installed as mentioned in package-lock.json
When you run `npm install` all the packages including the ones they depend upon should be installed automatically. Please try running the command again and let us know if the issue persists.

**Comment by mdew192837** [comment]
@abhaychawla  I received the error as I posted in the dpaste :)

**Comment by abhaychawla** [comment]
@mdew192837 You got the error when you ran npm start because the node-sass package didn't get installed. I am trying to explain to you that it must have been due to a network issue when you ran npm install. You must have received an error at that time. That is why I am asking you to again do the npm install and post its log if you get an error during installation again. Otherwise it should work fine as there is no issue with the current package.json
