### ISSUE TITLE
.travis.yml uses "npm run build:prod" but README says to use "ng build"

### ISSUE THREAD

**Issue by vorburger** [openMF/web-app#737]
https://github.com/openMF/web-app/blob/master/.travis.yml#L14 currently uses:

    npm run build:prod

but https://github.com/openMF/web-app#build documentation suggests to use:

    ng build

This seems inconsistent (to a noob). Which one is correct?

PS: Also the `npm run build:prod` produces a weird index.html containing a `<base href="/web-app/">`, which seems broken. The `dist/index.html` produced by `ng build` seems to work better.

**Comment by karantakalkar** [comment]
@vorburger kindly see #436 and #437

**Comment by karantakalkar** [comment]
I guess we need to update docs

**Comment by abhaychawla** [comment]
@vorburger It has been done to create a production build with Travis and deploy it to Github pages due to which it is different. Due to the large size of the project we also had to increase the heap size for the production build as notified by Karan above . Although, we should mention the difference in `README.md` to avoid the confusion.

**Comment by shobhi1310** [comment]
@karantakalkar can I work on this issue, if so do assign me, I will review the docs and change at appropriate places.

**Comment by shubhamkorde** [comment]
I can help with this.

**Comment by vinmehta16** [comment]
> I can help with this.

I can help with this too. Please let me know!!
